[package]
name = "olivia_secp256k1"
version = "0.0.1"
authors = [ "LLFourn <lloyd.fourn@gmail.com>" ]
edition = "2018"

[dependencies]
olivia_core = { path = "../olivia_core" }
schnorr_fun = { path = "../../secp256kfun/schnorr_fun", features = ["serde"] }
diesel = { version = "1.4", default-features = false, optional = true }
serde  = { version = "1", default-features = false }
lazy_static = "1"
sha2 = "0.9"


[features]
libsecp_compat = ["schnorr_fun/libsecp_compat"]
